User/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
from Courses.chart_view import enrollment_chart


urlpatterns = [
    path('instructor_register/', views.register_instructor, name ="instructor_register"),
    path('student_register/', views.register_student, name = "student_register"),
    path('user_login/', views.user_login, name = "user_login"),
    path('user_logout/', views.user_logout, name = "user_logout"),
    path('about_us', views.aboutus, name = "about_us"),
    path('student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('instructor_dashboard/', views.instructor_dashboard, name = "instructor_dashboard"),
]


urlpatterns += [
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'authentication/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'authentication/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'authentication/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'authentication/password_reset_complete.html'), name='password_reset_complete'),
] 


urlpatterns+= [    path('enrollment_chart/', enrollment_chart, name='enrollment_chart'),
]
'''

urlpatterns += [
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
     path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
]

'''

mathify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Courses import urls as course_urls
from User import urls as User_urls
import django_ckeditor_5.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(course_urls)),
    path('', include(User_urls)),
    path('ckeditor5/', include(django_ckeditor_5.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import User

roles = (
    ('student', "Student"),
    ('Instructor', "Instructor"),
)

Gender = (
    ('M', "Male"),
    ('F', "Female"),
)

class StudentRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['gender'].required = True
        self.fields['first_name'].label = "First Name :"
        self.fields['last_name'].label = "Last Name :"
        self.fields['password1'].label = "Password :"
        self.fields['password2'].label = "Confirm Password :"
        self.fields['email'].label = "Email :"
        self.fields['gender'].label = "Gender :"

        self.fields['first_name'].widget.attrs.update(
            {
                'placeholder': 'Enter First Name',
            }
        )
        self.fields['last_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Last Name',
            }
        )
        self.fields['email'].widget.attrs.update(
            {
                'placeholder': 'Enter Email',
            }
        )
        self.fields['password1'].widget.attrs.update(
            {
                'placeholder': 'Enter Password',
            }
        )
        self.fields['password2'].widget.attrs.update(
            {
                'placeholder': 'Confirm Password',
            }
        )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'gender']

    def clean_gender(self):
        gender = self.cleaned_data.get('gender')
        if not gender:
            raise forms.ValidationError("Gender is required")
        return gender

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = "Student"
        if commit:
            user.save()
        return user


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(strip=False, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(email=email, password=password)
            if self.user is None:
                raise forms.ValidationError("Invalid email or password.")
            if not self.user.is_active:
                raise forms.ValidationError("This account is inactive.")

        return super().clean(*args, **kwargs)
    
    def get_user(self):
        return self.user

class InstructorRegistrationForm(UserCreationForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}), required=True)
    profile_picture = forms.ImageField(required=True, widget=forms.FileInput(attrs={'class': 'form-control'}))
    facebook = forms.URLField(max_length=200, required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))
    twitter = forms.URLField(max_length=200, required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))
    linkedin = forms.URLField(max_length=200, required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))
    instagram = forms.URLField(max_length=200, required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['gender'].required = True
        self.fields['first_name'].label = "First Name :"
        self.fields['last_name'].label = "Last Name :"
        self.fields['password1'].label = "Password :"
        self.fields['password2'].label = "Confirm Password :"
        self.fields['email'].label = "Email :"
        self.fields['gender'].label = "Gender :"

        self.fields['first_name'].widget.attrs.update({'placeholder': 'Enter First Name'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Enter Last Name'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Enter Email'})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Enter Password'})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Confirm Password'})

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'gender', 'bio', 'profile_picture', 'facebook', 'twitter', 'linkedin', 'instagram']

    def clean_gender(self):
        gender = self.cleaned_data.get('gender')
        if not gender:
            raise forms.ValidationError("Gender is required")
        return gender

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = "Instructor"
        if commit:
            user.save()
        return user


class StudentProfileEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'placeholder': 'Enter First Name'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Enter Last Name'})

    class Meta:
        model = User
        fields = ["first_name", "last_name", "gender"]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name', 
            'last_name', 
            'email', 
            'profile_picture', 
            
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'required': False}),
            'last_name': forms.TextInput(attrs={'required': False}),
            'email': forms.EmailInput(attrs={'required': False}),
            'profile_picture': forms.ClearableFileInput(attrs={'required': False}),
            
        }

class InstructorProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'bio',
            'email',
            'profile_picture',
            'facebook',
            'instagram',
            'linkedin',
            'twitter',
        ]

    def __init__(self, *args, **kwargs):
        super(InstructorProfileForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            if field.widget.__class__.__name__ != 'FileInput':
                field.widget.attrs.update({'class': 'form-control'})
            else:
                field.widget.attrs.update({'class': 'form-control-file'})

templates/instructors/categories.html
{% extends "coursepage/base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'category.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="main-content">
        <h2>Categories Of Maths</h2>
        <div class="categories-grid">
            {% for i in category %}
            <div class="category-card">
                <p>{{ i.name }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/instructors/course_add.html
{% extends "coursepage/base.html" %}

{% block content %}

<div class="container">
    <h2>Add Course</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group row mt-3">
            <label for="id_first_name" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                {{ form.title}}
                {% if form.title.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.title.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group row mt-3">
            <label for="id_first_name" class="col-sm-2 col-form-label">Language</label>
            <div class="col-sm-10">
                {{ form.Language}}
                {% if form.Language.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.Language.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        
        <div class="form-group row mt-3">
            <label for="id_first_name" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                {{ form.text}}
                {% if form.text.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.text.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        
        <div class="form-group row mt-3">
            <label for="id_first_name" class="col-sm-2 col-form-label">Category</label>
            <div class="col-sm-10">
                {{ form.category}}
                {% if form.category.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.category.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        
        <div class="form-group row mt-3">
            <label for="id_first_name" class="col-sm-2 col-form-label">Price</label>
            <div class="col-sm-10">
                {{ form.price}}
                {% if form.price.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.price.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        
        <div class="form-group row mt-3">
            <label for="id_first_name" class="col-sm-2 col-form-label">Level</label>
            <div class="col-sm-10">
                {{ form.level}}
                {% if form.level.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.level.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        
        <div class="form-group row mt-3">
            <label for="id_first_name" class="col-sm-2 col-form-label">Duration</label>
            <div class="col-sm-10">
                {{ form.duration}}
                {% if form.duration.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.duration.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        
        <div class="form-group row mt-3">
            <label for="id_first_name" class="col-sm-2 col-form-label">Upload Course Image</label>
            <div class="col-sm-10">
                {{ form.image}}
                {% if form.image.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.image.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Add Course</button>
    </form>
</div>
<br> </br>

{% endblock %}

templates/instructors/course_edit.html
{% extends 'coursepage/base.html' %}

{% block style %}

<style>
h1
{
    text-align : center;
}

</style>
{% endblock %}
{% block content %}
<h1> Edit Course Details </h1>
<div class="container mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
            <label for="title" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="title" name="title" value="{{ form.title.value }}">
            </div>
        </div>
        <div class="form-group row">
            <label for="text" class="col-sm-2 col-form-label">Text</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="text" name="text" value="{{ form.text.value }}">
            </div>
        </div>
        <div class="form-group row">
            <label for="category" class="col-sm-2 col-form-label">Category</label>
            <div class="col-sm-10">
                {{ form.category }}
                {% if form.category.errors %}
                    <div class="invalid-feedback">
                        {{ form.category.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        
        <div class="form-group row">
            <label for="price" class="col-sm-2 col-form-label">Price</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="price" name="price" value="{{ form.price.value }}">
            </div>
        </div>
        <div class="form-group row">
            <label for="level" class="col-sm-2 col-form-label">Level</label>
            <div class="col-sm-10">
                {{ form.level}}
                {% if form.level.errors %}
                    <div class="invalid-feedback">
                        {{ form.level.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="duration" class="col-sm-2 col-form-label">Duration</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="duration" name="duration" value="{{ form.duration.value }}">
            </div>
        </div>
        <div class="form-group row">
            <label for="Language" class="col-sm-2 col-form-label">Language</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="Language" name="Language" value="{{ form.Language.value }}">
            </div>
        </div>
        <div class="form-group row">
            <label for="image" class="col-sm-2 col-form-label">Image</label>
            <div class="col-sm-10">
                <input type="file" class="form-control-file" id="image" name="image">
                {% if form.instance.image %}
                    <img src="{{ form.instance.image.url }}" alt="Image" class="mt-2" height="100">
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
    {% for section in item %}
            <div class="list-group-item">
                <h5>{{ section.title }}</h5>
                <a href="{% url 'section_edit' course_id=course.pk section_id=section.pk %}" class="btn btn-primary btn-sm">Edit Section</a>
            </div>
        {% endfor %}
        <br>
</div>

{% endblock %}

templates/instructors/instructor_dashboard.html
{% extends 'coursepage/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Profile & settings</h2>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="true">Profile & settings</button>
        </li>
       
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <form method="post" action="{% url 'instructor_dashboard' %}" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="form-group row mt-3">
                    <label for="id_first_name" class="col-sm-2 col-form-label">First Name</label>
                    <div class="col-sm-10">
                        {{ form.first_name }}
                        {% if form.first_name.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.first_name.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                
                <div class="form-group row mt-3">
                    <label for="id_first_name" class="col-sm-2 col-form-label">Bio</label>
                    <div class="col-sm-10">
                        {{ form.bio}}
                        {% if form.bio.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.bio.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="id_last_name" class="col-sm-2 col-form-label">Last Name</label>
                    <div class="col-sm-10">
                        {{ form.last_name }}
                        {% if form.last_name.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.last_name.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="id_email" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-10">
                        {{ form.email }}
                        {% if form.email.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.email.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="id_facebook" class="col-sm-2 col-form-label">Facebook</label>
                    <div class="col-sm-10">
                        {{ form.facebook }}
                        {% if form.facebook.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.facebook.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="id_instagram" class="col-sm-2 col-form-label">Instagram</label>
                    <div class="col-sm-10">
                        {{ form.instagram }}
                        {% if form.instagram.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.instagram.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="id_linkedin" class="col-sm-2 col-form-label">LinkedIn</label>
                    <div class="col-sm-10">
                        {{ form.linkedin }}
                        {% if form.linkedin.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.linkedin.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="id_twitter" class="col-sm-2 col-form-label">Twitter</label>
                    <div class="col-sm-10">
                        {{ form.twitter }}
                        {% if form.twitter.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.twitter.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <form method="post" action="{% url 'instructor_dashboard' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group row mt-3">
                        <label for="id_profile_picture" class="col-sm-2 col-form-label">Profile Picture</label>
                        <div class="col-sm-10">
                            <input type="file" name="profile_picture" id="id_profile_picture" class="form-control-file" onchange="previewImage(event)">
                            {% if form.profile_picture.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ form.profile_picture.errors }}
                                </div>
                            {% endif %}
                            <div class="mt-2">
                                <p>Minimum 200x200 pixels, Maximum 6000x6000 pixels</p>
                                <div id="image-preview">
                                    {% if user.profile_picture %}
                                        <img src="{{ user.profile_picture.url }}" alt="Profile Picture" class="img-fluid" id="profile-picture-preview" height="200">
                                    {% else %}
                                        <p>No profile picture uploaded</p>
                                        <img id="profile-picture-preview" class="img-fluid" height="200" style="display:none;">
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                     
                    </div>
                </form>
                
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </form>
        </div>
           

    </div>

    <hr>
    
    <div class="container mt-5">
        <h2>My Courses</h2>
        <div class="row">
            {% for item in instructor_courses %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <div class="card-img-container">
                            <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.title }}">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ item.title }}</h5>
                            <p class="card-text">{{ item.text|truncatewords:15 }}</p>
                            <p class="card-text"><small class="text-muted">Level: {{ item.level }}</small></p>
                            <p class="card-text"><strong>₹{{ item.price }}</strong></p>
                        </div>
                        <div class="card-footer d-flex justify-content-between">
                            <a href="{% url 'course_description' item.pk %}" class="btn btn-primary btn-sm me-1">View Course</a>
                            <a href="{% url 'course_edit' item.pk %}" class="btn btn-primary btn-sm me-1">Edit Course</a>
                            <a href="{% url 'add_section' item.pk %}" class="btn btn-primary btn-sm me-1">Add Section</a>
                            <a href = "{% url 'course_delete' item.pk %}" class ="btn btn-secondary btn-sm me-1"> Delete Course</a>
                        </div>
                    </div>                                                                                          
                </div>
            {% endfor %}
        </div>
    </div>


    <br>
<h2>Course Enrollments Over Time</h2>
<img src="{% url 'enrollment_chart' %}" alt="Course Enrollments Over Time">
</div>
{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-beta2/js/bootstrap.bundle.min.js"></script>

<script>
function previewImage(event) {
    var reader = new FileReader();
    reader.onload = function(){
        var output = document.getElementById('profile-picture-preview');
        output.src = reader.result;
        output.style.display = 'block';
    };
    reader.readAsDataURL(event.target.files[0]);
}
</script>
{% endblock %}