User/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
from Courses.chart_view import enrollment_chart


urlpatterns = [
    path('instructor_register/', views.register_instructor, name ="instructor_register"),
    path('student_register/', views.register_student, name = "student_register"),
    path('user_login/', views.user_login, name = "user_login"),
    path('user_logout/', views.user_logout, name = "user_logout"),
    path('about_us', views.aboutus, name = "about_us"),
    path('student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('instructor_dashboard/', views.instructor_dashboard, name = "instructor_dashboard"),
]


urlpatterns += [
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'authentication/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'authentication/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'authentication/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'authentication/password_reset_complete.html'), name='password_reset_complete'),
] 


urlpatterns+= [    path('enrollment_chart/', enrollment_chart, name='enrollment_chart'),
]
'''

urlpatterns += [
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
     path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
]

'''

mathify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Courses import urls as course_urls
from User import urls as User_urls
import django_ckeditor_5.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(course_urls)),
    path('', include(User_urls)),
    path('ckeditor5/', include(django_ckeditor_5.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from .account import CustomUserManager


roles = (
    ('student', "Student"),
    ('Instructor', "Instructor"),
)

Gender = (
    ('M', "Male"),
    ('F', "Female"),
)

class User(AbstractUser):
    role = models.CharField(choices=roles, max_length=14)
    gender = models.CharField(choices=Gender, max_length=7)
    email = models.EmailField(unique=True, blank=False, error_messages={'unique': "A user with that email already exists."})
    username = None
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    profile_picture = models.ImageField(upload_to="instructors/", default="default.png")
    facebook = models.URLField(max_length=200, blank=True, null=True)
    twitter = models.URLField(max_length=200, blank=True, null=True)
    linkedin = models.URLField(max_length=200, blank=True, null=True)    
    instagram = models.URLField(max_length=200, blank=True, null=True)
    bio = models.TextField(null = True, blank = True)
    def __str__(self):
        return f"{self.email}"
    
    def get_full_name(self):
        return self.first_name + ' ' + self.last_name
    
    def get_initials(self):
        return ''.join(list(self.first_name[0] + self.last_name[0]))
        
    groups = models.ManyToManyField(
        Group,
        related_name='custom_user_set',  
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        verbose_name='groups',
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='custom_user_permissions_set',  # Add a unique related_name
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )
    objects = CustomUserManager()


class Searches(models.Model):
    searcher = models.ForeignKey(User, on_delete= models.CASCADE)
    search_term = models.CharField(max_length= 200)
    timestamp = models.DateTimeField(auto_now_add= True)

User/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import User

roles = (
    ('student', "Student"),
    ('Instructor', "Instructor"),
)

Gender = (
    ('M', "Male"),
    ('F', "Female"),
)

class StudentRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['gender'].required = True
        self.fields['first_name'].label = "First Name :"
        self.fields['last_name'].label = "Last Name :"
        self.fields['password1'].label = "Password :"
        self.fields['password2'].label = "Confirm Password :"
        self.fields['email'].label = "Email :"
        self.fields['gender'].label = "Gender :"

        self.fields['first_name'].widget.attrs.update(
            {
                'placeholder': 'Enter First Name',
            }
        )
        self.fields['last_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Last Name',
            }
        )
        self.fields['email'].widget.attrs.update(
            {
                'placeholder': 'Enter Email',
            }
        )
        self.fields['password1'].widget.attrs.update(
            {
                'placeholder': 'Enter Password',
            }
        )
        self.fields['password2'].widget.attrs.update(
            {
                'placeholder': 'Confirm Password',
            }
        )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'gender']

    def clean_gender(self):
        gender = self.cleaned_data.get('gender')
        if not gender:
            raise forms.ValidationError("Gender is required")
        return gender

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = "Student"
        if commit:
            user.save()
        return user


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(strip=False, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(email=email, password=password)
            if self.user is None:
                raise forms.ValidationError("Invalid email or password.")
            if not self.user.is_active:
                raise forms.ValidationError("This account is inactive.")

        return super().clean(*args, **kwargs)
    
    def get_user(self):
        return self.user

class InstructorRegistrationForm(UserCreationForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}), required=True)
    profile_picture = forms.ImageField(required=True, widget=forms.FileInput(attrs={'class': 'form-control'}))
    facebook = forms.URLField(max_length=200, required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))
    twitter = forms.URLField(max_length=200, required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))
    linkedin = forms.URLField(max_length=200, required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))
    instagram = forms.URLField(max_length=200, required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['gender'].required = True
        self.fields['first_name'].label = "First Name :"
        self.fields['last_name'].label = "Last Name :"
        self.fields['password1'].label = "Password :"
        self.fields['password2'].label = "Confirm Password :"
        self.fields['email'].label = "Email :"
        self.fields['gender'].label = "Gender :"

        self.fields['first_name'].widget.attrs.update({'placeholder': 'Enter First Name'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Enter Last Name'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Enter Email'})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Enter Password'})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Confirm Password'})

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'gender', 'bio', 'profile_picture', 'facebook', 'twitter', 'linkedin', 'instagram']

    def clean_gender(self):
        gender = self.cleaned_data.get('gender')
        if not gender:
            raise forms.ValidationError("Gender is required")
        return gender

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = "Instructor"
        if commit:
            user.save()
        return user


class StudentProfileEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'placeholder': 'Enter First Name'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Enter Last Name'})

    class Meta:
        model = User
        fields = ["first_name", "last_name", "gender"]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name', 
            'last_name', 
            'email', 
            'profile_picture', 
            
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'required': False}),
            'last_name': forms.TextInput(attrs={'required': False}),
            'email': forms.EmailInput(attrs={'required': False}),
            'profile_picture': forms.ClearableFileInput(attrs={'required': False}),
            
        }

class InstructorProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'bio',
            'email',
            'profile_picture',
            'facebook',
            'instagram',
            'linkedin',
            'twitter',
        ]

    def __init__(self, *args, **kwargs):
        super(InstructorProfileForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            if field.widget.__class__.__name__ != 'FileInput':
                field.widget.attrs.update({'class': 'form-control'})
            else:
                field.widget.attrs.update({'class': 'form-control-file'})

templates/authentication/login.html
{% extends 'coursepage/base.html' %}

{% block content %}

{% load static %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="row w-100">
        <div class="col-md-6 d-none d-md-flex align-items-center justify-content-center">
            <img src="{% static 'background.jpeg' %}" alt="Sign up illustration" class="img-fluid">
        </div>
        <div class="col-md-6 d-flex flex-column align-items-center">
            <h2 class="mb-4 text-center">Sign up and start learning</h2>
            <form method="post" class="w-100" style="max-width: 400px;">
                {% csrf_token %}
                
                
                <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                    {% for error in form.email.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_password1">Password</label>
                    {{ form.password }}
                    {% for error in form.password.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
               
                <a href="{% url 'password_reset' %}"><i>Forgot Password?</i></a>
                <button type="submit" class="btn btn-primary btn-block">Sign up</button>
                {% if form.non_field_errors %}
                    <div class="text-danger mt-3">{{ form.non_field_errors }}</div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/authentication/password_reset_complete.html
{% extends "coursepage/base.html" %}
{% block title %}Password reset{% endblock %}

{% block style %}
<style>
.centered-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh; /* Adjust this if needed to fit your layout */
    text-align: center;
}
</style>
{% endblock %}
{% block content %}

<div class = "centered-container">
<h1>Password set</h1>
<p>Your password has been set. You can <a href="{% url "user_login" %}">log in now</a>
</p>
</div>
{% endblock %}

templates/authentication/password_reset_confirm.html
{% extends "coursepage/base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="." method="post">
 {{ form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Change my password" /></p>
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has
 already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

templates/authentication/password_reset_done.html
{% extends "coursepage/base.html" %}
{% block title %}Reset your password{% endblock %}

{% block style %}
<style>
    .centered-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh; /* Adjust this if needed to fit your layout */
        text-align: center;
    }
    h1 {
        margin-bottom: 20px; /* Adjust this as needed */
    }
</style>
{% endblock %}

{% block content %}
<div class="centered-container">
    <h1>Reset your password</h1>
    <p>We've emailed you instructions for setting your password.</p>
    <p>If you don't receive an email, please make sure you've entered the address you registered with.</p>
</div>
{% endblock %}

templates/authentication/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link
below:
{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.first_name }} {{user.last_name}}

templates/authentication/password_reset_form.html
{% extends "coursepage/base.html" %}

{% block style %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
    }

    .container {
        flex: 1;
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 15px;
    }

    footer {
        margin-top: auto;
    }

    .card {
        width: 100%;
        max-width: 500px;
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .btn {
        margin-top: 1rem;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center" style="width: 100%;">
        <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                <div class="card-header justify-content-center">
                    <div id="error_div"></div>
                    <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                </div>
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <div id="form_errors">
                            {% for key, value in form.errors.items %}
                                <strong>{{ value }}</strong>
                            {% endfor %}
                        </div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-md-10 offset-md-1">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_email">Email</label>
                                    <input type="email" name="email" class="form-control"
                                           autocomplete="email" maxlength="254" required id="id_email"
                                           placeholder="Enter email">
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-10 offset-md-1">
                                <div class="form-group mt-0 mb-1">
                                    <button type="submit" class="btn btn-dark btn-block">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <div class="small">
                        <a href="{% url 'user_login' %}">Back To Login</a><br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/authentication/register_instructor.html
{% extends 'coursepage/base.html' %}

{% block content %}

{% load static %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="row w-100">
        <div class="col-md-6 d-none d-md-flex align-items-center justify-content-center">
            <img src="{% static 'background.jpeg' %}" alt="Sign up illustration" class="img-fluid">
        </div>
        <div class="col-md-6 d-flex flex-column align-items-center">
            <h2 class="mb-4 text-center">Sign up and start teaching</h2>
            <form method="post" enctype="multipart/form-data" class="w-100" style="max-width: 400px;">
                {% csrf_token %}
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    {{ form.first_name }}
                    {% for error in form.first_name.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    {{ form.last_name }}
                    {% for error in form.last_name.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    {{ form.email }}
                    {% for error in form.email.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="gender">Gender</label>
                    {{ form.gender }}
                    {% for error in form.gender.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    {{ form.password1 }}
                    {% for error in form.password1.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    {{ form.password2 }}
                    {% for error in form.password2.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="bio">Bio</label>
                    {{ form.bio }}
                    {% for error in form.bio.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="profile_picture">Profile Picture</label>
                    {{ form.profile_picture }}
                    {% for error in form.profile_picture.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="facebook">Facebook</label>
                    {{ form.facebook }}
                    {% for error in form.facebook.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="twitter">Twitter</label>
                    {{ form.twitter }}
                    {% for error in form.twitter.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="linkedin">LinkedIn</label>
                    {{ form.linkedin }}
                    {% for error in form.linkedin.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="instagram">Instagram</label>
                    {{ form.instagram }}
                    {% for error in form.instagram.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Register</button>

                <br> </br>
                {% if form.non_field_errors %}
                    <div class="text-danger mt-3">{{ form.non_field_errors }}</div>
                {% endif %}
            </form>
           
        </div>
    </div>
</div>
{% endblock %}

templates/authentication/register_student.html
{% extends 'coursepage/base.html' %}

{% block content %}

{% load static %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="row w-100">
        <div class="col-md-6 d-none d-md-flex align-items-center justify-content-center">
            <img src="{% static 'background.jpeg' %}" alt="Sign up illustration" class="img-fluid">
        </div>
        <div class="col-md-6 d-flex flex-column align-items-center">
            <h2 class="mb-4 text-center">Sign up and start learning</h2>
            <form method="post" class="w-100" style="max-width: 400px;">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_first_name">First Name</label>
                    {{ form.first_name }}
                    {% for error in form.first_name.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    {{ form.last_name }}
                    {% for error in form.last_name.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                    {% for error in form.email.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_password1">Password</label>
                    {{ form.password1 }}
                    {% for error in form.password1.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_password2">Confirm Password</label>
                    {{ form.password2 }}
                    {% for error in form.password2.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_gender">Gender</label>
                    {{ form.gender }}
                    {% for error in form.gender.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Sign up</button>
                {% if form.non_field_errors %}
                    <div class="text-danger mt-3">{{ form.non_field_errors }}</div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}